### PR TITLE
Update to zig 0.13.0

### PR DESCRIPTION
**Pull request by PalanixYT**
I've tried to update the codebase. All tests and examples compile/pass.
Sadly zig fmt fucked up everything. If you're still willing to merge, that would be great. If not, you can just snatch the edits from this pr

### CODE REVIEW

**Comment by PalanixYT** [comment]
Oh my apologies then! I thought that those tags referred to the zig version they compile against

**Comment by PalanixYT** [comment]
I've tried doing it and I've found two things:
- Test and basic-app fail because `displayCmdInfo` is missing the last boolean
- basic-app will fail because `writeFile` isn't called correctly. You can find the fix in my pr

**Comment by 00JCIV00** [comment]
> Oh my apologies then! I thought that those tags referred to the zig version they compile against

That's understandable, haha. If you have any further thoughts on how I can delineate that, I'm open to suggestions. 

> I've tried doing it and I've found two things:
> - Test and basic-app fail because `displayCmdInfo` is missing the last boolean
> - basic-app will fail because `writeFile` isn't called correctly. You can find the fix in my pr though

Good find! I'll have those updated quickly next time I'm at a computer. A big part of the v0.11 update is setting up proper tests to avoid some of these smaller mistakes.

**Comment by PalanixYT** [comment]
> > Oh my apologies then! I thought that those tags referred to the zig version they compile against
> 
> That's understandable, haha. If you have any further thoughts on how I can delineate that, I'm open to suggestions.
The thing that made me think most that those tags refer to older versions was that the documentation still had slightly older code syntax and I projected that idea on the entire code.

That being said, just from the looks of this project, this is insane. It's downright beautiful what cova can do with comptime

**Comment by 00JCIV00** [comment]
Much appreciated! I'll continue to work on the README so it lines up better with the latest Zig trends. More importantly though, I'm glad Cova's comptime features drew you in. I've still got a few more features in the works that I think you'll really like.

Separately, those issues have been resolved on the latest v0.10.1 commit. Thanks again.

**Pull request closed without merging**
